<a href="https://colab.research.google.com/github/jgxbos/DL_examples/blob/main/Ejemplo_MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Flatten


In [7]:
model = Sequential()
model.add( Flatten(input_shape = (28,28)))

In [8]:
from keras.layers import Dense #Fully connected layers
model.add(Dense(512, activation = 'relu')) #Añadimos dos capas densas (fully connected de 512 neuronas)
model.add(Dense(512, activation = 'relu'))

model.add(Dense(10, activation = 'softmax')) #Añadimos capa softmax de salida con 10 nueronas, problemas nmist

In [ ]:
A=np.array([[[1],[2]],[[3],[4]]])

In [ ]:
print(A)

[[[1]
  [2]]

 [[3]
  [4]]]


In [ ]:
A.shape


(2, 2, 1)

In [ ]:
np.random.randn(3,4)+np.random.randn(1,4)

array([[-0.3334961 , -2.64514861, -2.76902696,  0.74756856],
       [ 0.85810806, -2.19988319, -3.15740936,  1.41827399],
       [-2.04720872, -0.88827393, -0.31226032, -0.12238186]])

In [ ]:
np.array([[1,1],[1,-1]])

array([[ 1,  1],
       [ 1, -1]])

In [ ]:
t_x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])


In [ ]:
x_exp=np.exp(t_x)
x_sum=np.sum(x_exp,axis=1)

In [ ]:
x_sum

array([8260.88614278, 1248.04631753])

In [3]:
x = np.random.rand(3, 2)

In [4]:
y = np.sum(x, axis=0, keepdims=True)

In [5]:
y.shape

(1, 2)